fixed error with switch
SEIIGruppe2/App pull request #67
Opened 2024-05-15 18:32 UTC by TimonWoelbitsch

2024-05-16 08:11 UTC, Manuel1598 commented on app/src/main/java/com/example/munchkin/activity/MainGameActivity.java
Fängst du hier nun beide SWITCH_CARD_PLAYER_RESPONSE ab oder nur den SWITCH_CARD_PLAYER_RESPONSE1 da du den anderen rausgelöscht hast und wenn dieser nicht abgefangen wird stürzt der Server ab.
Wo wird sonst der SWITCH_CARD_PLAYER_RESPONSE abgefangen?

2024-05-16 08:12 UTC, Manuel1598 commented on app/src/main/java/com/example/munchkin/controller/GameController.java
Hier das selbe wie oben.

2024-05-16 08:13 UTC, Manuel1598 requested changes
Bitte kurz auf die Fragen eingehen und falls dies alles beachtet wurde bitte erneut den Request anfrage. DANKE !

2024-05-16 14:55 UTC, TimonWoelbitsch commented on app/src/main/java/com/example/munchkin/activity/MainGameActivity.java
in der carddekactivity

2024-05-16 14:55 UTC, TimonWoelbitsch commented on app/src/main/java/com/example/munchkin/controller/GameController.java
siehe oben

2024-05-18 09:09 UTC, Manuel1598 approved these changes

2024-05-18 16:11 UTC, merged