80 resolve code smells
SEIIGruppe2/App pull request #81
Opened 2024-06-17 14:53 UTC by Manuel1598

This pull request encompasses a series of refactoring steps aimed at improving the readability, maintainability, and performance of our codebase.

## General Improvements

### Code Clean-up
- Removed unused classes, methods, imports, and commented-out code to declutter the codebase.

### Method Renaming
- Renamed methods for better clarity and consistency.

### Variable Renaming
- Renamed variables to enhance readability and understanding.

### Optimization
- Simplified conditional statements and removed redundant code to improve performance and readability.

## Specific Changes

### Error Handling
- Enhanced error handling by removing unnecessary logs.
- Added necessary comments to empty methods for better understanding.

### Logical Simplifications
- Converted complex switch-cases to simpler if-else structures.

Closes #80

2024-06-17 16:49 UTC, TimonWoelbitsch approved these changes

2024-06-17 22:32 UTC, Y1Egger requested changes

2024-06-17 22:32 UTC, Y1Egger commented on app/src/main/java/com/example/munchkin/view/MainGameView.java
List<Button> "Zone1Monster" vlt ändern in "zone1Monster"?

2024-06-18 07:38 UTC, Manuel1598 commented on app/src/main/java/com/example/munchkin/view/MainGameView.java
Das hat er anscheinend nicht richtig übernommen gehabt, hab es nun geändert. Vielen Dank

2024-06-18 08:50 UTC, RenaT0Pl approved these changes

2024-06-18 09:27 UTC, Y1Egger approved these changes

2024-06-18 09:55 UTC, merged